CREATE TABLE `dots`.`dots_doc_type` 
(`ID` INT NOT NULL AUTO_INCREMENT 
, `DOC_TYPE_NAME` VARCHAR(255) NOT NULL 
, `DOC_TYPE_CODE` VARCHAR(255) NOT NULL 
, PRIMARY KEY (`ID`)) ENGINE = InnoDB;

CREATE TABLE `dots`.`dots_doc_prps` 
(`ID` INT NOT NULL AUTO_INCREMENT 
, `DOC_PRPS_NAME` VARCHAR(255) NOT NULL 
, `DOC_PRPS_CODE` VARCHAR(255) NOT NULL 
, PRIMARY KEY (`ID`)) ENGINE = InnoDB;

CREATE TABLE `dots`.`dots_doc_office` 
(`ID` INT NOT NULL AUTO_INCREMENT 
, `DOC_OFFICE_NAME` VARCHAR(255) NOT NULL 
, `DOC_OFFICE_CODE` VARCHAR(255) NOT NULL 
, PRIMARY KEY (`ID`)) ENGINE = InnoDB;

CREATE TABLE `dots`.`dots_doc_division` 
(`ID` INT NOT NULL AUTO_INCREMENT 
, `DOC_DIVISION_NAME` VARCHAR(255) NOT NULL 
, `DOC_DIVISION_CODE` VARCHAR(255) NOT NULL 
, PRIMARY KEY (`ID`)) ENGINE = InnoDB;

CREATE TABLE `DOTS`.`DOTS_ACCOUNT` (
  `HRIS_ID` int(11) NOT NULL,
  `FULL_NAME` varchar(255) NOT NULL,
  `INITIAL` varchar(255) NOT NULL,
  `USERNAME` varchar(255) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL
) ENGINE=InnoDB;


CREATE TABLE `dots`. (`DOC_NUM` INT NOT NULL AUTO_INCREMENT 
, `RECEIVED_BY` VARCHAR(255) NOT NULL 
, `DATE_TIME_RECEIVED` VARCHAR(255) NOT NULL 
, `LETTER_DATE` VARCHAR(255) NOT NULL 
, `DOC_TYPE` VARCHAR(255) NOT NULL 
, `DOC_OFFICE` VARCHAR(255) NOT NULL 
, `DOC_SUBJECT` VARCHAR(255) NOT NULL 
, PRIMARY KEY (`DOC_NUM`)) ENGINE = InnoDB;