CREATE TABLE `dots`.`dots_doc_type` 
(`ID` INT NOT NULL AUTO_INCREMENT 
, `DOC_TYPE_NAME` VARCHAR(255) NOT NULL 
, `DOC_TYPE_CODE` VARCHAR(255) NOT NULL 
, PRIMARY KEY (`ID`)) ENGINE = InnoDB;

CREATE TABLE `dots`.`dots_doc_prps` 
(`ID` INT NOT NULL AUTO_INCREMENT 
, `DOC_PRPS_NAME` VARCHAR(255) NOT NULL 
, `DOC_PRPS_CODE` VARCHAR(255) NOT NULL 
, PRIMARY KEY (`ID`)) ENGINE = InnoDB;

CREATE TABLE `dots`.`dots_doc_office` 
(`ID` INT NOT NULL AUTO_INCREMENT 
, `DOC_OFFICE_NAME` VARCHAR(255) NOT NULL 
, `DOC_OFFICE_CODE` VARCHAR(255) NOT NULL 
, PRIMARY KEY (`ID`)) ENGINE = InnoDB;