const _RESET_TIME = 5000;

const _REQUEST = {
    INSERT: 'INSERT',
    SELECT: 'SELECT',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    GET_DATE: 'GET_DATE',
    GET_DOC_NUM: 'GET_DOC_NUM',
    CREATE_SESSION: 'CREATE_SESSION',

    INSERT_DOCLOG: 'INSERT_DOCLOG',

    USER_LOGIN: 'USER_LOGIN',

    GET_SESSION_NAME: 'GET_SESSION_NAME',
    GET_SESSION_INITIAL: 'GET_SESSION_INITIAL',
    GET_SESSION_HRIS_ID: 'GET_SESSION_HRIS_ID',
    GET_SESSION_DEPT_ID: 'GET_SESSION_DEPT_ID',

    GET_DOCUMENT: 'GET_DOCUMENT',
    EDIT_DOCUMENT: 'EDIT_DOCUMENT',

    CANCEL_RECEIVE: 'CANCEL_RECEIVE',
    CANCEL_SEND: 'CANCEL_SEND',

    GET_DOC_NUM: 'GET_DOC_NUM',
    GET_DOC_TYPE: 'GET_DOC_TYPE',
    GET_DOC_OFFICE: 'GET_DOC_OFFICE',
    GET_DOC_PRPS: 'GET_DOC_PRPS',
    GET_DEPT: 'GET_DEPT',
    GET_ADDRESSEE: 'GET_ADDRESSEE',
    GET_ATTACHMENT: 'GET_ATTACHMENT',

    SEND_DOC_FORM: 'SEND_DOC_FORM',
    RECEIVE_DOC: 'RECEIVE_DOC',

    GET_TABLE_MAIN: 'GET_TABLE_MAIN',
    GET_TABLE_INBOUND: 'GET_TABLE_INBOUND',
    GET_TABLE_OUTBOUND: 'GET_TABLE_OUTBOUND',
    GET_TABLE_ATTACHMENT: 'GET_TABLE_ATTACHMENT',
    GET_TABLE_TRACKING: 'GET_TABLE_TRACKING',

    GET_FILTER_YEAR: 'GET_FILTER_YEAR',

    ATTACH_ADD: 'ATTACH_ADD',

    RECEIVE_DOC_USER: 'RECEIVE_DOC_USER',
    SEND_DOC_USER: 'SEND_DOC_USER',

}
