const _RESET_TIME = 1000;

const DOTS_DOCUMENT = {
    NAME: 'DOTS_DOCUMENT',
    DOC_NUM: 'DOC_NUM',
    LETTER_DATE: 'LETTER_DATE',
    DOC_TYPE: 'DOC_TYPE',
    DOC_SUBJECT: 'DOC_SUBJECT',
    DOC_LOCATION: 'DOC_LOCATION',
    DATE_TIME_RECEIVED: 'DATE_TIME_RECEIVED',
    DOC_STATUS: 'DOC_STATUS',
};
const DOTS_DOC_OFFICE = {
    NAME: 'DOTS_DOC_OFFICE',
    ID: 'ID',
    DOC_OFFICE_NAME: 'DOC_OFFICE_NAME',
    DOC_OFFICE_CODE: 'DOC_OFFICE_CODE'
};

const DOTS_DOC_DIVISION = {
    NAME: 'DOTS_DOC_DIVISION',
    ID: 'ID',
    DOC_DIVISION_NAME: 'DOC_DIVISION_NAME',
    DOC_DIVISION_CODE: 'DOC_DIVISION_CODE'
};
const DOTS_DOC_TYPE = {
    NAME: 'DOTS_DOC_TYPE',
    ID: 'ID',
    DOC_TYPE_NAME: 'DOC_TYPE_NAME',
    DOC_TYPE_CODE: 'DOC_TYPE_CODE'
};

const DOTS_DOC_PRPS = {
    NAME: 'DOTS_DOC_PRPS',
    ID: 'ID',
    DOC_PRPS_NAME: 'DOC_PRPS_NAME',
    DOC_PRPS_CODE: 'DOC_PRPS_CODE'
};
const DOTS_DOC_STATUS = {

    NAME: 'DOTS_DOC_STATUS',
    ID: 'ID',
    DOC_STATUS_NAME: 'DOC_STATUS_NAME',
    DOC_STATUS_CODE: 'DOC_STATUS_CODE'
};
const DOTS_ACCOUNT = {
    NAME: 'DOTS_ACCOUNT',
    HRIS_ID: 'HRIS_ID',
    FULL_NAME: 'FULL_NAME',
    INITIAL: 'INITIAL',
    USERNAME: 'USERNAME',
    PASSWORD: 'PASSWORD',
}

const DOC_STATUS = {
    NAME: 'DOC_STATUS',
    ID: 'ID',
    DOC_STATUS_NAME: "DOC_STATUS",
}
const _REQUEST = {
    INSERT: 'INSERT',
    SELECT: 'SELECT',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    GET_DATE: 'GET_DATE',
    GET_DOC_NUM: 'GET_DOC_NUM',
    CREATE_SESSION: 'CREATE_SESSION',
    INSERT_DOUBLE_ID: 'INSERT_DOCLOG',
    GET_SESSION_NAME: 'GET_SESSION_NAME',
    GET_SESSION_INITIAL: 'GET_SESSION_INITIAL',
}

const _SUB_NAME = {

    ID: "ID",

    DOC_TYPE_NAME: 'Document Name',
    DOC_TYPE_CODE: 'Document Code',

    DOC_PRPS_NAME: 'Purpose Name',
    DOC_PRPS_CODE: 'Purpose Code',

    DOC_OFFICE_NAME: 'Office Name',
    DOC_OFFICE_CODE: 'Office Code',

    DOC_DIVISION_NAME: 'Division Name',
    DOC_DIVISION_CODE: 'Division Code',

    DOC_STATUS_NAME: 'Status',
    DOC_STATUS_CODE: 'Status Code',

    DOC_NUM: 'No.',
    DOC_SUBJECT: 'Subject',
    LETTER_DATE: 'Letter Date',
    DOC_TYPE: 'Document Type',
    OFFICE_AGENCY: 'Office/Agency',
    DOC_LOCATION: 'Location',
    DATE_TIME_RECEIVED: 'Date Received',
    DOC_STATUS: "Status"
}
